# Generated by Django 5.2.7 on 2025-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driverRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('mobileNumber', models.IntegerField(max_length=10)),
                ('aadharId', models.IntegerField(max_length=12)),
            ],
        ),
    ]
