# Generated by Django 5.2.7 on 2025-12-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='driverRegistration',
            new_name='partnerRegistration',
        ),
    ]
