# Generated by Django 5.2.7 on 2025-12-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0002_rename_driverregistration_partnerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='carDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=50)),
                ('vehicleNumber', models.CharField(max_length=15)),
                ('vehicleType', models.CharField(max_length=20)),
                ('seatingCapacity', models.IntegerField()),
                ('rentPerDay', models.IntegerField()),
                ('availabilityStatus', models.BooleanField(default=True)),
                ('vehicleImage', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalPartner.partnerregistration')),
            ],
        ),
    ]
