# Generated by Django 5.2.7 on 2025-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0003_cardetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='fuelType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
