# Generated by Django 5.2.7 on 2025-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0004_cardetails_fueltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='GST_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='combanyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
