# Generated by Django 5.2.7 on 2026-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0005_partnerregistration_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
