# Generated by Django 5.2.7 on 2026-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0006_partnerregistration_address_partnerregistration_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_images/'),
        ),
    ]
