# Generated by Django 5.2.7 on 2026-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0007_partnerregistration_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerregistration',
            old_name='image',
            new_name='profileImage',
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='aadharImage',
            field=models.ImageField(blank=True, null=True, upload_to='partner_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='shopImage',
            field=models.ImageField(blank=True, null=True, upload_to='partner_documents/shop/'),
        ),
        migrations.AlterField(
            model_name='partnerregistration',
            name='aadharId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerregistration',
            name='mobileNumber',
            field=models.IntegerField(),
        ),
    ]
