# Generated by Django 5.2.7 on 2026-01-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0008_rename_image_partnerregistration_profileimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerregistration',
            name='verified',
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
