# Generated by Django 5.2.7 on 2026-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalPartner', '0009_remove_partnerregistration_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
