# Generated by Django 5.2.7 on 2025-12-27 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='registrationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
