# Generated by Django 5.2.7 on 2025-12-29 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userregistration_registrationdate'),
        ('rentalPartner', '0004_cardetails_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=38)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('pickupLocation', models.CharField(max_length=100)),
                ('dropLocation', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('numberOfDays', models.IntegerField()),
                ('preferredTime', models.TimeField()),
                ('paymentMethod', models.BooleanField(default=False)),
                ('confirmStatus', models.BooleanField(default=False)),
                ('bookingStatus', models.BooleanField(default=True)),
                ('carRentPerDay', models.IntegerField()),
                ('carName', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalPartner.cardetails')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalPartner.partnerregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
        ),
    ]
