# Generated by Django 5.2.7 on 2025-12-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='Additionalnotes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
