# Generated by Django 5.2.7 on 2025-12-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookingdetails_additionalnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='bookingStatus',
            field=models.BooleanField(default=False),
        ),
    ]
