# Generated by Django 5.2.7 on 2025-12-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookingdetails_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
