# Generated by Django 5.2.7 on 2025-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userregistration_age_userregistration_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='connected_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
