# Generated by Django 5.2.7 on 2026-01-01 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userregistration_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectedTravelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected', models.BooleanField(default=False)),
                ('connected_accepted', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('reply', models.CharField(blank=True, max_length=200, null=True)),
                ('connected_traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_traveler', to='home.userregistration')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
        ),
    ]
