# Generated by Django 5.2.7 on 2026-01-05 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_connectedtravelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='bookingDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
