# Generated by Django 5.2.7 on 2026-01-08 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookingdetails_bookingdate'),
        ('rentalPartner', '0007_partnerregistration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupLocation', models.CharField(max_length=100)),
                ('dropLocation', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('numberOfDays', models.IntegerField()),
                ('preferredTime', models.TimeField()),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('paymentMethod', models.BooleanField(default=False)),
                ('confirmStatus', models.BooleanField(default=False)),
                ('bookingStatus', models.BooleanField(default=False)),
                ('fareperday', models.IntegerField()),
                ('carName', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalPartner.cardetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistration')),
            ],
        ),
    ]
