# Generated by Django 5.2.7 on 2026-01-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_driverbooking'),
        ('partner', '0004_driverregistration_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.driverregistration'),
        ),
    ]
