# Generated by Django 5.2.7 on 2026-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_driverbooking_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='userProfile/'),
        ),
    ]
