# Generated by Django 5.2.7 on 2026-01-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userregistration_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
