# Generated by Django 5.2.7 on 2026-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userregistration_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='budgetRange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='favDestinations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='travelpreferences',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
