# Generated by Django 5.2.7 on 2025-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='licenceImage',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licences/'),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='licenceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='phoneNumber',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
    ]
