# Generated by Django 5.2.7 on 2025-12-27 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_driverregistration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='driverJoinedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
