# Generated by Django 5.2.7 on 2025-12-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_driverregistration_driverjoineddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
