# Generated by Django 5.2.7 on 2026-01-14 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_driverregistration_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='driverJoinedDate',
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='joinedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='aadharId',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='licenceNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
