# Generated by Django 5.2.7 on 2026-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_driverregistration_driverjoineddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='location',
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
