# Generated by Django 5.2.7 on 2026-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_driverregistration_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverregistration',
            name='aadharImage',
            field=models.ImageField(blank=True, null=True, upload_to='driver_aadhars/'),
        ),
    ]
