# Generated by Django 5.2.7 on 2026-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_driverregistration_aadharimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverregistration',
            old_name='city',
            new_name='bank_account',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='licenceType',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='state',
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='licenceExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
