# Generated by Django 5.2.7 on 2026-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_rename_city_driverregistration_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='driver_fee',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='licenceExpiry',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='location',
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='licenceType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driverregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
