# Generated by Django 5.2.7 on 2026-02-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_rename_city_driverregistration_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverregistration',
            name='aadharId',
        ),
        migrations.RemoveField(
            model_name='driverregistration',
            name='aadharImage',
        ),
    ]
